// tfjs-react-native/integration_rn59/App.tsx
/**
 * @license
 * Copyright 2019 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

import React, { Fragment } from 'react';
import {
  Button,
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import * as tf from '@tensorflow/tfjs';
import '@tensorflow/tfjs-react-native';

import Diagnostic from './components/Diagnostic';
import MobilenetDemo from './components/MobilenetDemo';

export type Screen = 'main' | 'diag' | 'demo';

interface AppState {
  isTfReady: boolean;
  currentScreen: Screen;
}

export default class App extends React.Component<any, AppState> {
  constructor(props: any) {
    super(props);
    this.state = {
      isTfReady: false,
      currentScreen: 'main'
    }

    this.showDiagnosticScreen = this.showDiagnosticScreen.bind(this);
    this.showDemoScreen = this.showDemoScreen.bind(this);
    this.showMainScreen = this.showMainScreen.bind(this);
  }

  async componentDidMount() {
    await tf.setBackend('rn-webgl');
    await tf.ready();
    this.setState({
      isTfReady: true,
    });
  }

  showDiagnosticScreen() {
    this.setState({ currentScreen: 'diag' });
  }

  showDemoScreen() {
    this.setState({ currentScreen: 'demo' });
  }

  showMainScreen() {
    this.setState({ currentScreen: 'main' });
  }

  renderMainScreen() {
    return <Fragment>
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Diagnostic</Text>
        <Button
          onPress={this.showDiagnosticScreen}
          title="Show Diagnostic Screen"
        />
      </View>
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Demo</Text>
        <Button
          onPress={this.showDemoScreen}
          title="Show Demo Screen"
        />
      </View>
    </Fragment>;
  }

  renderDiagnosticScreen() {
    return <Fragment>
      <Diagnostic returnToMain={this.showMainScreen} />
    </Fragment>
  }

  renderDemoScreen() {
    const image = require('./assets/images/catsmall.jpg');
    return <Fragment>
      <MobilenetDemo
        image={image}
        returnToMain={this.showMainScreen} />
    </Fragment>
  }

  renderLoadingTF() {
    return <Fragment>
      <View style={styles.sectionContainer}>
        <Text style={styles.sectionTitle}>Loading TF</Text>
      </View>
    </Fragment>
  }

  renderContent() {
    const { currentScreen, isTfReady } = this.state;
    if (isTfReady) {
      switch (currentScreen) {
        case 'main':
          return this.renderMainScreen();
        case 'diag':
          return this.renderDiagnosticScreen();
        case 'demo':
          return this.renderDemoScreen();
        default:
          return this.renderMainScreen();
      }
    } else {
      return this.renderLoadingTF();
    }

  }

  render() {
    return (
      <Fragment>
        <StatusBar barStyle="dark-content" />
        <SafeAreaView>
          <ScrollView
            contentInsetAdjustmentBehavior="automatic"
            style={styles.scrollView}>

            <View style={styles.body}>
              {this.renderContent()}
            </View>
          </ScrollView>
        </SafeAreaView>
      </Fragment>
    );
  }
}

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: 'white',
  },
  body: {
    backgroundColor: 'white',
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: 'black',
    marginBottom: 6,
  },
});

// demos/game_of_life/App.vue
<!-- Copyright 2017 Google Inc. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================-->
<template>
  <div>
    <demo-header name="Game-of-Life deep-learning demo"></demo-header>
    <div class="app">
      <div class="train">
        <table class="train-controls">
          <tr>
            <td>Board size:</td>
            <td>
              <input type="text" id="board-size-input" value="5">
            </td>
          </tr>
          <tr>
            <td>Training size:</td>
            <td>
              <input type="text" id="training-size-input" value="2000">
            </td>
          </tr>
          <tr>
            <td>Training batch size:</td>
            <td>
              <input type="text" id="training-batch-size-input" value="5">
            </td>
          </tr>
          <tr>
            <td>Learning rate:</td>
            <td>
              <input type="text" id="learning-rate-input" value="1.0">
            </td>
          </tr>
          <tr>
            <td>Number of layers:</td>
            <td>
              <input type="text" id="num-layers-input" value="3">
            </td>
          </tr>
          <tr>
            <td>Update Interval:</td>
            <td>
              <input type="text" id="update-interval-input" value="25">
            </td>
          </tr>
          <tr>
            <td>Use Log Cost:</td>
            <td>
              <input type="checkbox" id="use-log-cost-input" checked="checked">
            </td>
          </tr>
          <tr>
            <td colspan="2" class="buttons">
              <button class="add-sequence-button">Add Sequence</button>
              <button class="train-button">Train Model</button>
              <button class="reset-button">Reset</button>
            </td>
          </tr>
        </table>

        <div class="train-console">
          <div>
            <span class="train-display">Waiting to train.</span>
            <span class="data-display"></span>
          </div>
          <div class="train-graph">
            <canvas id="myChart" width="500" height="300" style="background-color: #ccc;"></canvas>
          </div>
        </div>

        <div class="clearfix"></div>
      </div>

      <div class="worlds-display"></div>
    </div>
    <demo-footer></demo-footer>
  </div>
</template>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
<script src="./app.ts"></script>

<style scoped>
  .world {
    display: inline-block;
  }

  .world+.world {
    margin-left: 20px;
  }

  .board {
    background-color: #cccccc;
    display: inline-block;
    padding: 5px;
  }

  .column {
    min-height: 20px;
    min-width: 20px;
    display: inline-block;
    margin: 1px;
  }

  .column.alive {
    background-color: #333333;
  }

  .column.dead {
    background-color: #ffffff;
  }

  .worlds-display {
    /* float: left; */
    padding: 20px;
  }

  .train {
    margin-left: auto;
    margin-right: auto;
    max-width: 80%;
    border-bottom: 1px dashed #333333;
    padding: 20px 0;
  }

  .train-controls {
    float: left;
  }

  .train-console {
    float: right;
  }

  .clearfix {
    clear: both;
  }

  .buttons {
    padding: 15px 0;
  }

  .train-display {
    color: #333333;
    text-decoration: underline;
  }
</style>
